travis:
  secure:
    BINSTAR_TOKEN: wvne8BF9OYRswge+8tb3IQeBxjMclXkB74LNWypTfGx6gtT0EbSf4bZRzoxlB2bQZXr7b8WKNONQTeM9/wCVTTiuAQSUOXMmiXA2hxEMq+TEcSzyRZ3cfHOdWS47eBJv5Vk/4pJCe6FLXb3OfvsV241UB9XLqfsBDcOkJUa5BLClVoL4gDkornmKO/UWaqs0KHBYAAFlEsHoCPUwtkzcqDeaHxifA7Gm3XqFLe8tcj4PRlV1zcBbAqHRoTOM6aK2hNoqvP0vsFrip+kOHQlCTvpZLlBwvkzU5YtXv8d5ZG/b/eYWi/2pHS84cdsbj96Ekq2MOC5wS3cAJLCodIIUjskLopBErtOyMTOKQ/d5LzV3SXLwxyg1b8NA+tcJ156IwXSqT9ZghLyHrXLSV2c5n7kdMQhb3x9cS2jjW5Ea9fzSjRhhoExF92n1gDGdPCLNK4G6ixBQSGQyCMEgK1g1pL/ErcgusAthiDfuSV0gePPvBTRHd5TPiny/ZT9/7btS0yAJ18UgVbRsxiDABz6V+mxS/HGvvgqTDrla00Zu42gF8+oZsG1aL772AF5HrdErWDSGyj/qYF0xIF9EjeaGjulYCLbBC6+fpd/VQMzMx2eaQqiys7oZ7Na2x7KISGuawDKIo54O+nGcjA6bFfjLEEu6OLkwZSfmXov+PKz/4l0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
